name: svls_automatic

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  check-updates:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: dalance/svls
          ref: master
      
      - name: Analyse
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format="%at" origin/master)
          CURRENT_DATE=$(date +%s)
          TIME_DIFF=$(( CURRENT_DATE - LAST_COMMIT_DATE ))
          
          if [ $TIME_DIFF -le 86400 ]; then
            echo "There are updates within the last 24 hours."
            echo "updates-found=true" >> $GITHUB_OUTPUT
          else
            echo "No updates within the last 24 hours."
            echo "updates-found=false" >> $GITHUB_OUTPUT
          fi


  build:
    needs: check-updates
    if: |
      ${{ github.event_name == 'workflow_dispatch' 
          || needs.check-updates.outputs.updates-found == true
          || !contains(needs.check-updates.outputs.artifacts, 'svls-binary')
        }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: dalance/svls
          ref: master

      - name: Setup MUSL
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools

      - name: Build for linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl
          tar -czf svls-binary.tar.gz target/x86_64-unknown-linux-musl/release/svls
      
      - name: Save Binary
        uses: actions/upload-artifact@v2
        with:
          name: svls-binary
          path: svls-binary.tar.gz
